ITI System/Models/Instructor.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ITI_System.Models
{
    public class Instructor
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(50)]
        [MinLength(3)]
        public string Name { get; set; }
        [Required]

        public decimal salary { get; set; }
        [Required]
        [RegularExpression(@"^\w+\.(jpg|png)$", ErrorMessage = "Image must be in jpg or png format")]

        public string imageUrl { get; set; }

        public string address { get; set; }

        [Display(Name = "Department")]
        public int deptId { get; set; }
        [ForeignKey("deptId")]
        public Department department { get; set; }
        [Display(Name = "Course")]
        public int crsId { get; set; }
        [ForeignKey("crsId")]
        public Course? course { get; set; }
    }
}

ITI System/Controllers/InstructorController.cs
using ITI_System.Models;
using ITI_System.Repositry;
using ITI_System.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ITI_System.Controllers
{
    [Authorize]
    public class InstructorController : Controller
    {
        IinstructorRepositry instructorRepositry;
        ICrsReprositry crsRepositry;
        IDeptReprositry deptRepositry;
        public InstructorController(IinstructorRepositry inst ,ICrsReprositry crs,IDeptReprositry dept)
        {
            instructorRepositry = inst;
            crsRepositry = crs;
            deptRepositry = dept;
        }


        public IActionResult Details()
        {
            List<Instructor> instModel = instructorRepositry.GetAll();
            return View("instructor_view",instModel);
        }

        public IActionResult insdetails(int id)
        {
            Instructor instModel = instructorRepositry.instDetails(id);
            return View("instructor_details", instModel);
        }
        public IActionResult Edit(int id)
        {

           
            InstAndCrsList instfromrequest = instructorRepositry.Edit(id);
            return View("instructor_edit", instfromrequest);
        }
        public IActionResult SaveEdit(int id, InstAndCrsList instfromrequest)
        {
            Instructor instDB = instructorRepositry.GetById(id);
            if (instfromrequest.Name!=null)
            {
                instfromrequest.Id = id;
                instDB.Name = instfromrequest.Name;
                instDB.salary = instfromrequest.salary;
                instDB.imageUrl = instfromrequest.imageUrl;
                instDB.address = instfromrequest.address;
                instDB.deptId = instfromrequest.deptId;
                instDB.crsId = instfromrequest.crsId;


                instructorRepositry.update(instDB);
                instructorRepositry.save();
                return RedirectToAction("Details");
            }
            instfromrequest.courses = crsRepositry.GetAll();
            instfromrequest.departments = deptRepositry.GetAll();
            return View("instructor_edit", instfromrequest );
        }

        public IActionResult Add()
        {
            listdepartment_listcrs_instructor? model= new listdepartment_listcrs_instructor();
            model.deptoptions =deptRepositry.GetAllDeptsWithNameandId();
            model.crsoptions = crsRepositry.GetAllCrsWithNameandId();
            return View("New",model);

        }
        [HttpPost]
        public IActionResult Savenew(listdepartment_listcrs_instructor instfromRequest)
        { Instructor instdb=new Instructor();
            if (instfromRequest.salary >= 4500&&instfromRequest.Name!=null)
            {
               
                
                    instdb.Name = instfromRequest.Name;
                    instdb.salary = instfromRequest.salary;
                    instdb.imageUrl = instfromRequest.imageUrl;
                    instdb.address = instfromRequest.address;
                    instdb.deptId = instfromRequest.deptId;
                    instdb.crsId = instfromRequest.crsId;

                    instructorRepositry.Add(instdb);
                instructorRepositry.save();
                return RedirectToAction("Details");
                
            }

            instfromRequest.deptoptions = deptRepositry.GetAllDeptsWithNameandId();
            instfromRequest.crsoptions = crsRepositry.GetAllCrsWithNameandId();
            return View("New", instfromRequest);
        }
        
        public IActionResult delete(int id)
        {
            instructorRepositry.delete(id);
            instructorRepositry.save();
            return RedirectToAction("Details");
        }
    }
}

ITI System/Views/Instructor/New.cshtml
@model listdepartment_listcrs_instructor
@{
	ViewData["Title"] = "Add New Instructor";
	
	

}
<div class="d-flex justify-content-center align-items-center vh-100 bg-light">
	<div class="card shadow-lg p-4 rounded-4" style="width: 400px; background-color: #ffffff;">
		<h2 class="text-center mb-4 text-primary">New Inst</h2>

<form asp-action="Savenew" asp-controller="Instructor" >
	
<div>
	
		<label asp-for="Name"></label>
		<input class="form-check form-control" asp-for="Name" />
		<span asp-validation-for="Name" class="text-danger"></span>

		<label asp-for="salary"></label>
		<input class="form-check form-control" asp-for="salary"/>

		<label asp-for ="imageUrl">
			</label>
		<input class="form-check form-control" asp-for="imageUrl"/>
		<span asp-validation-for="imageUrl"></span>

			<label asp-for ="address">
				</label>
		<input class="form-check form-control" asp-for="address" />

		<label asp-for="deptId"></label>
		<select class="form-check form-control" asp-for="deptId" asp-items="@Model.deptoptions" ></select>

		<label asp-for="crsId"></label>
		<select class="form-check form-control" asp-for="crsId" asp-items="@Model.crsoptions"></select>

		<br />
		<input type="submit" value="Save" class="btn btn-success" />

</div>
</form>
</div>
</div>

ITI System/Views/Instructor/instructor_details.cshtml
@model Instructor
@{
	ViewData["Title"] = "Instructor more Details";
}

<div class="card-body p-4">
	<table class="table table-bordered table-hover align-middle">
		<thead class="table-primary text-center">
	<tr>
		<th> Id</th>
		<th> Name</th>
		<th> Photo</th>
		<th> Salary</th>
		<th>Address</th>
		<th>course</th>
		<th>Department</th>
		
	</tr>
	<tr>
		<td>@(Model.Id-2)</td>
		<td>@Model.Name</td>
		<td><img src="/images/@Model.imageUrl" width="=50" height="50"/></td>
		<td>@Model.salary</td>
		<td>@Model.address</td>
		<td>@Model.course.Name</td>
		<td>@Model.department.Name</td>

	</tr>
</table>

ITI System/Views/Instructor/instructor_edit.cshtml
@model InstAndCrsList
@{
	ViewData["Title"] = "Edit Instructor";
}
<div class="d-flex justify-content-center align-items-center vh-100 bg-light">
	<div class="card shadow-lg p-4 rounded-4" style="width: 400px; background-color: #ffffff;">
		<h2 class="text-center mb-4 text-primary">Edit Details</h2>
<form  asp-action="SaveEdit" asp-controller="Instructor" asp-route-id="@Model.Id" method="post" class="form-control">
	<label class="form-label">Name</label>
	<input type="text" name="Name" value="@Model.Name" class="form-control" />
	<label class="form-label">salary</label>
	<input type="number" name="salary" value="@Model.salary" class="form-control" />
	<label class="form-label">address</label>
	<input type="text" name="address" value="@Model.address" class="form-control" />
	<label class="form-label">imageUrl</label>
	<input type="text" name="imageUrl" value="@Model.imageUrl" class="form-control" />
	@* <label>crsId</label>
	<input type="number" name="crsId" value="@Model.crsId" class="form-control" />
	<label>deptId</label>
	<input type="number" name="deptId" value="@Model.deptId" class="form-control" /> *@
	<br />
	<select name="crsId" class=" form-label">
		<option>---Select Course---</option>
		@foreach(var item in Model.courses)
		{
			if (Model.crsId == item.Id)
			{
				<option selected value="@item.Id">@item.Name</option>
			}
			else
			{
				<option value="@item.Id">@item.Name</option>
			}
		}
	</select>
	</<br /><br />
	<select name="deptId" class=" form-label">
		<option>---Select Dept---</option>
		@foreach (var item in Model.departments)
		{
			if (Model.deptId == item.ID)
			{
				
				<option selected value="@item.ID">@item.Name</option>
			}
			else
			{
				<option value="@item.ID">@item.Name</option>
			}
		}
	</select>
	<br /></<br /><br />
	<button type="submit" class="btn btn-primary btn-lg">Save</button>
	
</form>
</div>
</div>

ITI System/Views/Instructor/instructor_view.cshtml
@model List<Instructor>
@{
	ViewData["Title"] = "Instructor List";
	Layout = "_MyLayout";
}
@section option_section {
<p>View Our Instructors</p>
}
<div class="card-body p-4">
	<table class="table table-bordered table-hover ">
		<thead class="table-primary text-center">
			<tr>

				<th>Ins Name</th>
				<th>Ins Photo</th>
				@if(User.IsInRole("Admin"))
				{
					<th>Ins ID</th>
					<th>more details</th>
					<th>Edit details</th>
				}
				

	</tr>
	</thead>
	@foreach(var item in Model)
	{
		<tr>
			
			<td>@item.Name</td>
				<td><img src="/images/@item.imageUrl" width="100" /></td>
				@if (User.IsInRole("Admin"))
				{
				<td>@(item.Id - 2)</td>
			<td><a href="https://localhost:7059/Instructor/insdetails?id=@item.Id" class="btn btn-primary">view details</a></td>
			<td> <a href="/Instructor/Edit/@item.Id " class="btn btn-primary">Edit</a></td>
				}
		</tr>
	}

	

</table>
@if(User.IsInRole("Admin"))
				{
	<a asp-action="Add" asp-controller="Instructor" class="btn btn-primary btn-lg" >Add New</a>
				}
</div>