ITI System/Controllers/CourseController.cs
using ITI_System.Models;
using ITI_System.Repositry;
using ITI_System.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ITI_System.Controllers
{
    [Authorize]
    public class CourseController : Controller
    {
        ICrsReprositry crsRepositry ;
        IDeptReprositry deptRepositry ;
        public CourseController(IDeptReprositry deptobj, ICrsReprositry crsobj)
        {
            crsRepositry = crsobj;
            deptRepositry = deptobj;
        }
        public IActionResult Index()
        {
            List<Course> crsList = crsRepositry.GetAll();
            return View("View_courses", crsList);
        }
        public IActionResult AddCourse()
        {
            ViewData["depts"] = deptRepositry.GetAll();
            return View("Add_Course");
        }
        public IActionResult SaveAdd(Course crsfrpmRequest)
        {
            if (ModelState.IsValid == true)
            {
                if (crsfrpmRequest.deptId != 0)
                {
                    crsRepositry.Add(crsfrpmRequest);
                    crsRepositry.save();
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(nameof(crsfrpmRequest.deptId), "Please select a department.");
                }
            }
            ViewData["depts"] = deptRepositry.GetAll();
            return View("Add_Course");

        }
        public IActionResult checkname(string Name)
        {
            if (Name.Contains("ITI"))
            {
                return Json(true);
            }
            else
            {
                return Json(false);
            }
        }
        public IActionResult checkdegree(int degree, int minDegree)
        {
            if (degree > minDegree)
            {
                return Json(true);
            }
            else
            {
                return Json(false);
            }
        }

        public IActionResult Edit(int id)
        {
            ViewData["depts"] = deptRepositry.GetAll();

            Course crsfromdb = crsRepositry.GetById(id);
            if (crsfromdb == null)
            {
                return NotFound();
            }
            return View("Edit_Course", crsfromdb);

        }
        public IActionResult saveEdit(int id, Course coursefromrequest)
        {
            Course crsfromdb = crsRepositry.GetById(id);
            if (coursefromrequest.Name == crsfromdb.Name)
            {
                ModelState.Remove(nameof(coursefromrequest.Name));
            }
            if (ModelState.IsValid == true)
            {
                crsfromdb.Name = coursefromrequest.Name;
                crsfromdb.degree = coursefromrequest.degree;
                crsfromdb.minDegree = coursefromrequest.minDegree;
                crsfromdb.hours = coursefromrequest.hours;
                crsfromdb.deptId = coursefromrequest.deptId;
                crsRepositry.update(crsfromdb);
                crsRepositry.save();
                return RedirectToAction("Index");

            }
            ViewData["depts"] = deptRepositry.GetAll();
            return View("Edit_Course", coursefromrequest);
        }
        public IActionResult Course_Result(int id)
        {
            List<crsResult> results = crsRepositry.GetCourseResultByID(id);

            if (!results.Any())
            {
                return View("No_trainee");
              
            }
            return View("Course_Result", results);
        }


    }
}

ITI System/Controllers/DeptController.cs
using ITI_System.Models;
using ITI_System.Repositry;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ITI_System.Controllers
{
    [Authorize]   
    public class DeptController : Controller
    {
        IDeptReprositry deptRepositry;
        public DeptController(IDeptReprositry deptobj)
        {
            deptRepositry = deptobj;
        }
        
        public IActionResult Index()
        {
            List<Department> dept = deptRepositry.GetAll();
            return View("index", dept);
        }

        public IActionResult Add()
        {
            return View();
        }

        public IActionResult saveAdd(Department dept)
        {
            if (dept != null)
            {
                deptRepositry.Add(dept);
                deptRepositry.save();
                return RedirectToAction("Index");
            }
            return View("Add");
        }

       
    }
}

ITI System/Controllers/RoleController.cs
using ITI_System.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ITI_System.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }
        [HttpGet]
        public IActionResult AddRole()
        {
            return View("AddRole");
        }
        [HttpPost]
        public async Task<IActionResult> AddRole(RoleViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                //mapping
                IdentityRole role = new IdentityRole();
                role.Name = roleViewModel.RoleName;
                IdentityResult result = await roleManager.CreateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("AddRole");

                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError("", item.Description);
                    }
                }
            }
                return View("AddRole");

        }


    }
}

        
    

ITI System/Controllers/traineeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ITI_System.Models;
using ITI_System.ViewModels;
using ITI_System.Repositry;
using Microsoft.AspNetCore.Authorization;

namespace ITI_System.Controllers
{
    [Authorize]
    public class traineeController : Controller
    {
        ItraineeRepositry traineeRepositry;
        IcrsResultRepositry crsRepositry;
        public traineeController(ItraineeRepositry trainee, IcrsResultRepositry crs)
        {
            traineeRepositry = trainee;
            crsRepositry = crs;

        }
        public IActionResult FormResult()
        {
            return View("FormResult");
        }

        [HttpPost]
        public IActionResult showResult(int traineeId, int crsId)
        {
            crsesult_traineeInfo result = new crsesult_traineeInfo();
            var resultfromdb=crsRepositry.getresultfortrainee_in_hisCourses(traineeId, crsId);

            if (resultfromdb != null)
            {
                result.traineeid = resultfromdb.traineeId;
                result.TraineeName = resultfromdb.traineeName;
                result.CourseName = resultfromdb.course.Name;
                result.degree = resultfromdb.degree;
                result.MaxDegree = resultfromdb.course.degree;
                if (result.degree > resultfromdb.course.minDegree)
                {
                    result.state = "Passed";
                    result.color = "table-success";
                }
                else
                {
                    result.state = "Failed";
                    result.color = "table-danger";
                }
            }
           
            else
            {
                ViewBag.Message = "No result found for this Trainee and Course.";
                return View("NotFoundResult");
            }

           

            return View("TableResult", result);
        }

        

    }
}

ITI System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ITI_System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ITI_System.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ITI_System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ITI_System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ITI System/Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>ITI System</title>
    <link rel="icon" type="/image/x-icon" href="/assets/favicon.ico" />
    <link href="/css/styles.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body id="page-top">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
        <div class="container px-4">
            <a class="navbar-brand" href="#page-top">ITI System</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" asp-action="index" asp-controller="Home">Home</a></li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item"><a class="nav-link" asp-action="AddRole" asp-controller="Role">Add Role</a></li>
                        <li class="nav-item"><a class="nav-link" asp-action="index" asp-controller="ShowTraineesController1">Trainees</a></li>
                        <li class="nav-item"><a class="nav-link" asp-action="Details" asp-controller="Instructor">Instructors</a></li>
                        <li class="nav-item"><a class="nav-link" asp-action="index" asp-controller="Dept">Departments</a></li>
                        <li class="nav-item"><a class="nav-link" asp-action="index" asp-controller="Course">courses</a></li>
                    }
                    else
                    {
                        <li class="nav-item"><a class="nav-link" asp-action="Details" asp-controller="Instructor">Instructors</a></li>
                        <li class="nav-item"><a class="nav-link" asp-action="index" asp-controller="Dept">Departments</a></li>
                        <li class="nav-item"><a class="nav-link" asp-action="index" asp-controller="Course">courses</a></li>
                        <li class="nav-item"><a class="nav-link" asp-action="FormResult" asp-controller="trainee">Results</a></li>
                    }
                    @if (User.Identities.Any(i => i.IsAuthenticated) == false)
                    {
                        <li class="nav-item"><a class="nav-link" asp-action="Register" asp-controller="Account">Register</a></li>
                        <li class="nav-item"><a class="nav-link" asp-action="login" asp-controller="Account">Login</a></li>
                    }
                    else
                    {
                        <li class="nav-item"><a class="nav-link" asp-action="signout" asp-controller="Account">signout</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <header class="bg-primary bg-gradient text-white">
        <div class="container px-4 text-center">
            <h1 class="fw-bolder">@RenderSection("option_section", false)</h1>
        </div>
    </header>
    @RenderBody()
    @RenderSection("CustomSection", required: false)

  

    <footer class="py-5 bg-dark">
        <div class="container px-4"><p class="m-0 text-center text-white">Copyright &copy; ITI Website 2025</p></div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation-unobtrusive@4.0.0/dist/jquery.validate.unobtrusive.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="js/scripts.js"></script>
    @await RenderSectionAsync("scripts", false)
</body>
</html>